---
# 計測基盤の secret（gitignore 済み）。terraform/cloudflare の出力から生成。
pprotein_agent_tunnel_tokens:
  "1": "eyJhIjoiNzMzMWUzNThlMDI1MzUyMTY5OThjNDUxZmNiYzVlMGIiLCJ0IjoiYjQzZDAyN2YtMTMzOC00ZmRmLWE5ZWQtN2NlOGNhZWIwMTE5IiwicyI6IlQ2WmlJM3JGMWZaSXVvNlF0dXRITDBHbjRGaGtyNlRhY01hdGtSYXQzY0k9In0="
  "2": "eyJhIjoiNzMzMWUzNThlMDI1MzUyMTY5OThjNDUxZmNiYzVlMGIiLCJ0IjoiMmZmZjJjYTgtMGEyZC00NDVkLWI1NzAtZTljMzExZGVmNzhhIiwicyI6ImVKeWJMRTlsd3dWVjJHcHhDRDRQbGhjMnFUeHdhSjlOMmpMNThvMnhsMkE9In0="
  "3": "eyJhIjoiNzMzMWUzNThlMDI1MzUyMTY5OThjNDUxZmNiYzVlMGIiLCJ0IjoiZjNkOTgxOTEtNzc3ZS00MjQ0LTliMjktZGVkNzFhZWNhNmQwIiwicyI6IjZWVEpxT2d5QS9ZUmN4TDFQU2NoTThOV1FwcFB4YkFrbjJEajI2OFBnVGs9In0="
